cc_library(
    name = "http_sse_stream_proxy",
    srcs = ["http_sse_stream_proxy.cc"],
    hdrs = ["http_sse_stream_proxy.h"],
    deps = [
        "//trpc/client/http:http_stream_proxy",
        "//trpc/codec/http:http_protocol",
        "//trpc/stream/http/async:stream_reader_writer",
    ],
)
